version: 0.2

env:
  variables:
    TF_VERSION: "1.3.2"
    TFLINT_VERSION: "0.41.0"

phases:

  install:
    commands:
      - cd /usr/bin
      - "curl -s -qL -o terraform.zip https://releases.hashicorp.com/terraform/${TF_VERSION}/terraform_${TF_VERSION}_linux_amd64.zip"
      - unzip -o terraform.zip
      - "curl --location https://github.com/terraform-linters/tflint/releases/download/v${TFLINT_VERSION}/tflint_linux_amd64.zip --output tflint_linux_amd64.zip"
      - unzip -o tflint_linux_amd64.zip

  build:
    commands:
      - cd "$CODEBUILD_SRC_DIR"
      - terraform init
      - terraform validate
      - tflint --init
      - tflint

  post_build:
    commands:
      - echo "terraform validate completed on `date`"
      - echo "tflint completed on `date`"
